### PR TITLE
replace all chrome driver with node driver

### PR DESCRIPTION
**Pull request by Rosesqy**
pass npm i && npm run dev

### CODE REVIEW

**Comment by foreseaz** [comment]
LGTM, feel free to merge

**Comment by Rosesqy** [comment]
Just realized I do not have writing access to the repo. Can someone help me to merge the PR? Thank you!

**Comment by foreseaz** [comment]
Oh, I think you need to be in the org, I sent the invitation again, please accept that and try to merge. Let me know if there is any further questions. @Rosesqy

**Comment by Rosesqy** [comment]
Thank you! @foreseaz

**Pull request merged**
